version: "3.8"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3307:3306" # 测试用,从宿主机访问数据
    networks:
      - iothub
  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" # 测试用
    networks:
      - iothub
  iotsim:
    build: ./iotsim
    container_name: iotsim
    depends_on:
      - mosquitto
    networks:
      - iothub
  mqttsub:
    build: ./mqttsub
    container_name: mqttsub
    depends_on:
      - mosquitto
      - mysql
    networks:
      - iothub
  iotback:
    build: ./backend
    container_name: iotback
    ports:
      - "8080:8080" # 测试用, 宿主机启动前端访问
    expose:
      - 8080 
    depends_on:
      - mysql
    networks:
      - iothub
  iotfront:
    image: nginx
    container_name: iotfront
    ports:
      - "5173:80" 
    expose:
      - 80
    volumes:
      - "./frontend/dist:/usr/share/nginx/html"
      - "./frontend/nginx.conf:/etc/nginx/nginx.conf"
      - "./frontend/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - iotback
    networks:
      - iothub
networks:
  iothub:
    name: iotnet